### ISSUE TITLE
Errors upon Import

### ISSUE THREAD

**Issue by naxIO** [TzeC94/MirrorUnityFPS#35]
Hello there! Great project!

I downloaded this repo and opened it with the right unity version. out of the box the console is bleeding in errors. 

some due to using MyBox; whatever that is.

How can I fix them all, seems like some dependencies are missing!

Thanks

```
Rebuilding Library because the asset database could not be found!

An error occurred while resolving packages:
  Project has invalid dependencies:
    com.domybest.mybox: No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub
    com.veriorpies.parrelsync: No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub

A meta data file (.meta) exists but its folder 'Assets/StreamingAssets' can't be found, and has been created. Empty directories cannot be stored in version control, so it's assumed that the meta data file is for an empty directory in version control. When moving or deleting folders outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

Unable to update following assemblies:Assets/StarterAssets/Editor/PackageChecker/StarterAssetsPackageChecker.dll (Name = StarterAssetsPackageChecker, Error = 131) (Output: C:\Users\Chris\AppData\Local\Temp\tmp415aaed8.tmp)

System.IO.DirectoryNotFoundException: Could not find a part of the path 'I:\Unity Projects\newtry\MirrorUnityFPS-main\Library\PackageCache\com.domybest.mybox@7024455e9f'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at AssemblyUpdater.Core.AssemblyUpdaterContext.AddSubdirectoriesContainingDlls(String actualSearchPath, AssemblyResolver resolver)
   at AssemblyUpdater.Core.AssemblyUpdaterContext.ReadAssembly(String assemblyPath, IAPIUpdaterListener listener, FileAccess mode, String[] searchPaths)
   at AssemblyUpdater.Core.AssemblyUpdaterContext.From(String assemblyPath, ConfigurationProvider configuration, String[] assemblySearchPaths, IAPIUpdaterListener listener)
   at AssemblyUpdater.Core.AssemblyUpdaterContext.From(String assemblyPath, String[] assemblySearchPaths, IAPIUpdaterListener listener)
   at AssemblyUpdater.Application.Program.<>c__DisplayClass0_0.<Main>b__1(UpdateOptions o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at AssemblyUpdater.Application.Program.Main(String[] args)

UnityEditor.Scripting.APIUpdaterLogger:WriteErrorToConsole (string,object[])
UnityEditorInternal.APIUpdating.APIUpdaterManager:HandleAssemblyUpdaterErrors (System.Collections.Generic.IList`1<UnityEditorInternal.APIUpdating.AssemblyUpdaterUpdateTask>)
UnityEditorInternal.APIUpdating.APIUpdaterManager:UpdateAssemblies ()
UnityEditorInternal.APIUpdating.APIUpdaterManager:ProcessImportedAssemblies (string[])

Assets\Scripts\HeldItem\HeldBase.cs(3,7): error CS0246: The type or namespace name 'MyBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Input\Look At\LookAtPickup.cs(2,7): error CS0246: The type or namespace name 'MyBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Map Gen\Old\MapGeneration.cs(1,7): error CS0246: The type or namespace name 'MyBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Pickup\Item.cs(8,7): error CS0246: The type or namespace name 'MyBox' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Map Gen\Old\MapGeneration.cs(121,6): error CS0246: The type or namespace name 'ButtonMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Map Gen\Old\MapGeneration.cs(121,6): error CS0246: The type or namespace name 'ButtonMethod' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Map Gen\Old\MapGeneration.cs(132,6): error CS0246: The type or namespace name 'ButtonMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Map Gen\Old\MapGeneration.cs(132,6): error CS0246: The type or namespace name 'ButtonMethod' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\HeldItem\HeldBase.cs(14,6): error CS0246: The type or namespace name 'ReadOnlyAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\HeldItem\HeldBase.cs(14,6): error CS0246: The type or namespace name 'ReadOnly' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\HeldItem\HeldBase.cs(23,6): error CS0246: The type or namespace name 'ReadOnlyAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\HeldItem\HeldBase.cs(23,6): error CS0246: The type or namespace name 'ReadOnly' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Pickup\Item.cs(18,6): error CS0246: The type or namespace name 'ReadOnlyAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\Pickup\Item.cs(18,6): error CS0246: The type or namespace name 'ReadOnly' could not be found (are you missing a using directive or an assembly reference?)

Unloading broken assembly Library/ScriptAssemblies/Unity.Rider.Editor.dll, this assembly can cause crashes in the runtime


```

**Comment by TzeC94** [comment]
Hi ya, I think you're missing git on your PC, can you try and install this?
https://git-scm.com/

**Comment by naxIO** [comment]
Will do sure and saw this. but what about the other stuff?

**Comment by TzeC94** [comment]
Should be auto resolved after you got the Git installed, then try a reimport

**Comment by naxIO** [comment]
Fixed.
